
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/iris-contrib/middleware"
  version = "v10"

[[constraint]]
  branch = "master"
  name = "github.com/kataras/golog"

[[constraint]]
  name = "github.com/kataras/iris"
  version = "v10.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/kataras/pio"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v8"
  version = "8.18.2"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "v3.2.13"

[[constraint]]
  name = "github.com/hidevopsio/gorm"
  version = "2.0.1"
