# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: jwt-example
  profiles:
    include:
    - locale
    - logging
    - jwt
    - websocket

logging:
  level: info


