# default config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: hiboot
  profiles:
    include:
    - foo

logging:
  level: debug

# added for test only
fake:
  name: ${app.name}

foo: foo name

star:
  name: Earth
  system: solar